---
- id: renovate
  execute-command: /config/renovate-operator.sh
  pass-arguments-to-command:
    - # job name
      source: string
      name: homelab
    - # namespace
      source: string
      name: automation
    - # Renovate Operator webhook URL
      source: string
      name: http://renovate-operator.automation.svc.cluster.local:8082
    - # Forgejo event type header
      source: header
      name: X-Forgejo-Event
  pass-file-to-command:
    - # Entire request payload written to a temp file
      source: entire-payload
      envname: WEBHOOK_PAYLOAD_FILE
  trigger-rule:
    and:
      - # Validate the HMAC-SHA256 signature
        match:
          type: payload-hmac-sha256
          secret: >-
            {{ getenv "WEBHOOK_SECRET" }}
          parameter:
            source: header
            name: X-Forgejo-Signature
