---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-${APP}
spec:
  instances: 2

  primaryUpdateStrategy: unsupervised
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.6-0.5.3

  enableSuperuserAccess: true
  superuserSecret:
    name: ${APP}-cnpg-secret
  enablePDB: false
  bootstrap:
    initdb:
      database: ${APP}
      owner: ${APP}
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "384MB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "4MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "1310kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
    shared_preload_libraries:
      - "vchord.so"

  storage:
    storageClass: longhorn
    size: 10Gi
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cloudnative-pg/
      endpointURL: https://729991681d6b2d5c8f17351d354f4a92.r2.cloudflarestorage.com
      # Note: serverName version needs to be incremented
      # when recovering from an existing cnpg cluster
      serverName: postgres-${APP}-v1
      s3Credentials:
        accessKeyId:
          name: ${APP}-cnpg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: ${APP}-cnpg-secret
          key: aws-secret-access-key
  resources:
    requests:
      cpu: "100m"
    limits:
      memory: "1Gi"

  monitoring:
    enablePodMonitor: true
