---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: miniflux
    creationPolicy: Owner
    template:
      data:
        ADMIN_USERNAME: "{{ .username }}"
        ADMIN_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: miniflux
