---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kubevirt.io/kubevirt_v1.json
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - HostDevices
        - LiveMigration
        - NetworkBindingPlugins
    permittedHostDevices:
      usb:
        - resourceName: kubevirt.io/bluetooth
          selectors:
            - product: "0026"
              vendor: "8087"
    smbios:
      family: ccio
      manufacturer: Talos Virtualization
      product: talosvm
      sku: TalosCloud
      version: v0.1.0
  workloadUpdateStrategy:
    workloadUpdateMethods:
      - LiveMigrate
