---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmalertmanager-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vmalertmanager-secret
    creationPolicy: Owner
    template:
      data:
        DISCORD_WEBHOOK_URL: "{{ .webhook_url }}"
  dataFrom:
    - extract:
        key: discord
