---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics
  interval: 1h
  values:
    fullnameOverride: victoria-metrics

    prometheus-node-exporter:
      enabled: true
      fullnameOverride: node-exporter
      image:
        registry: quay.io
        repository: prometheus/node-exporter
      hostNetwork: false
      prometheus:
        monitor:
          enabled: true
          jobLabel: app.kubernetes.io/instance
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: nodename
            - action: replace
              regex: (.*)
              replacement: $1.internal:9100
              sourceLabels:
                - kubernetes_node
              targetLabel: instance
      resources:
        requests:
          cpu: 23m
          memory: 64M
        limits:
          memory: 64M

    kube-state-metrics:
      enabled: true
      fullnameOverride: kube-state-metrics
      prometheus:
        monitor:
          enabled: true
          honorLabels: true
      rbac:
        extraRules:
          - apiGroups:
              - source.toolkit.fluxcd.io
              - kustomize.toolkit.fluxcd.io
              - helm.toolkit.fluxcd.io
              - notification.toolkit.fluxcd.io
            resources:
              - gitrepositories
              - buckets
              - helmrepositories
              - helmcharts
              - ocirepositories
              - kustomizations
              - helmreleases
              - alerts
              - providers
              - receivers
            verbs:
              - list
              - watch
      customResourceState:
        enabled: true
        config:
          spec:
            resources:
              - groupVersionKind:
                  group: kustomize.toolkit.fluxcd.io
                  version: v1
                  kind: Kustomization
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux Kustomization resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - lastAppliedRevision
                      source_name:
                        - spec
                        - sourceRef
                        - name
              - groupVersionKind:
                  group: helm.toolkit.fluxcd.io
                  version: v2
                  kind: HelmRelease
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux HelmRelease resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - history
                        - "0"
                        - chartVersion
                      chart_name:
                        - status
                        - history
                        - "0"
                        - chartName
                      chart_app_version:
                        - status
                        - history
                        - "0"
                        - appVersion
                      chart_ref_name:
                        - spec
                        - chartRef
                        - name
                      chart_source_name:
                        - spec
                        - chart
                        - spec
                        - sourceRef
                        - name
              - groupVersionKind:
                  group: source.toolkit.fluxcd.io
                  version: v1
                  kind: HelmRepository
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux HelmRepository resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - artifact
                        - revision
                      url:
                        - spec
                        - url
              - groupVersionKind:
                  group: source.toolkit.fluxcd.io
                  version: v1
                  kind: HelmChart
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux HelmChart resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - artifact
                        - revision
                      chart_name:
                        - spec
                        - chart
                      chart_version:
                        - spec
                        - version
              - groupVersionKind:
                  group: source.toolkit.fluxcd.io
                  version: v1
                  kind: OCIRepository
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux OCIRepository resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      revision:
                        - status
                        - artifact
                        - revision
                      url:
                        - spec
                        - url
              - groupVersionKind:
                  group: notification.toolkit.fluxcd.io
                  version: v1beta3
                  kind: Alert
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux Alert resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      suspended:
                        - spec
                        - suspend
              - groupVersionKind:
                  group: notification.toolkit.fluxcd.io
                  version: v1beta3
                  kind: Provider
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux Provider resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      suspended:
                        - spec
                        - suspend
              - groupVersionKind:
                  group: notification.toolkit.fluxcd.io
                  version: v1
                  kind: Receiver
                metricNamePrefix: gotk
                metrics:
                  - name: resource_info
                    help: The current state of a Flux Receiver resource.
                    each:
                      type: Info
                      info:
                        labelsFromPath:
                          name:
                            - metadata
                            - name
                    labelsFromPath:
                      exported_namespace:
                        - metadata
                        - namespace
                      ready:
                        - status
                        - conditions
                        - "[type=Ready]"
                        - status
                      suspended:
                        - spec
                        - suspend
                      webhook_path:
                        - status
                        - webhookPath

    victoria-metrics-operator:
      fullnameOverride: victoria-metrics-operator
      crds:
        cleanup:
          image:
            repository: registry.k8s.io/kubectl

    vmcluster:
      enabled: false

    vmagent:
      spec:
        scrapeInterval: 30s
        externalLabels:
          cluster: home
        remoteWrite:
          - url: http://vmsingle-victoria-metrics.observability.svc.cluster.local:8428/api/v1/write
        extraArgs:
          promscrape.streamParse: "true"
          promscrape.maxScrapeSize: "32MB"
        inlineRelabelConfig:
          - action: drop
            source_labels:
              - __name__
            regex: "cpu_feature_.+"
          - action: drop
            source_labels:
              - __name__
            regex: "kubernetes_feature_enabled"
          - action: labeldrop
            regex: ".+_node_kubevirt_io_.+"
          - action: labeldrop
            regex: "kubevirt_io_.+"
          - action: labeldrop
            regex: "feature_node_kubernetes_io_.+"

    vmalert:
      spec:
        evaluationInterval: 30s
        externalLabels:
          cluster: home
        remoteWrite:
          url: http://vmsingle-victoria-metrics.observability.svc.cluster.local:8428/api/v1/write
        remoteRead:
          url: http://vmsingle-victoria-metrics.observability.svc.cluster.local:8428

    alertmanager:
      spec:
        externalURL: https://vmalertmanager.erwanleboucher.dev
        replicaCount: 1
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 5Gi
      useManagedConfig: true
      config:
        route:
          receiver: discord
          repeat_interval: 12h
          routes:
            - receiver: blackhole
              matchers:
                - alertname = InfoInhibitor
            - receiver: blackhole
              matchers:
                - alertname = Watchdog
            - receiver: blackhole
              matchers:
                - severity = info
            - receiver: discord
              matchers:
                - severity = critical
          group_by:
            - alertname
            - cluster
            - job
          group_interval: 5m
          group_wait: 1m
        inhibit_rules:
          - equal:
              - alertname
              - namespace
            source_matchers:
              - severity = "critical"
            target_matchers:
              - severity = "warning"
        receivers:
          - name: blackhole
          - name: discord
            discord_configs:
              - send_resolved: true
                title: |-
                  [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "critical" }}🔥{{ else if eq .CommonLabels.severity "warning" }}⚠️{{ else }}ℹ️{{ end }}{{ else }}✅{{ end }} {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }} {{ else if ne .CommonAnnotations.message ""}}{{ .CommonAnnotations.message }} {{ else if ne .CommonAnnotations.description ""}}{{ .CommonAnnotations.description }} {{ else }}{{ .CommonLabels.alertname }}{{ end }}
                message: |-
                  {{ range .Alerts -}}
                    **Alert:** {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

                  {{ if ne .Annotations.summary ""}}**Summary:** {{ .Annotations.summary }} {{ else if ne .Annotations.message ""}}**Message:** {{ .Annotations.message }} {{ else if ne .Annotations.description ""}}**Description:** {{ .Annotations.description }}{{ end }}

                  🏷 Labels:
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
                webhook_url_secret:
                  name: vmalertmanager-secret
                  key: DISCORD_WEBHOOK_URL
      route:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - vmalertmanager.erwanleboucher.dev

    vmsingle:
      enabled: true
      spec:
        retentionPeriod: 90d
        extraArgs:
          maxLabelsPerTimeseries: "40"
        storage:
          storageClassName: longhorn
          resources:
            requests:
              storage: 50Gi
      route:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - vmsingle.erwanleboucher.dev

    defaultDashboards:
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true

    defaultDatasources:
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true

    grafana:
      enabled: false
      forceDeployDatasource: true

    kubeControllerManager:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true

    kubeEtcd:
      service:
        selector:
          component: kube-apiserver
        port: 2381
        targetPort: 2381
      vmScrape:
        spec:
          endpoints:
            - scheme: http

    kubeScheduler:
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
