---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kanidm
spec:
  chartRef:
    kind: OCIRepository
    name: kanidm
  interval: 30m
  values:
    controllers:
      kanidm:
        replicas: 1
        type: statefulset
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: docker.io/kanidm/server
              tag: 1.9.2
            env:
              KANIDM_ADMIN_BIND_PATH: /var/run/kanidmd.sock
              KANIDM_DOMAIN: idm.erwanleboucher.dev
              KANIDM_ORIGIN: https://idm.erwanleboucher.dev
              KANIDM_BINDADDRESS: "[::]:8443"
              KANIDM_LDAPBINDADDRESS: "[::]:3636"
              KANIDM_DB_PATH: /data/kanidm.db
              KANIDM_TLS_CHAIN: /certs/tls.crt
              KANIDM_TLS_KEY: /certs/tls.key
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      provision:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: ghcr.io/m00nwtchr/kanidm-provision
              tag: 1.3.0
            env:
              KANIDM_INSTANCE: https://idm.erwanleboucher.dev
              KANIDM_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: kanidm-provision-token
                    key: token
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 100Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    persistence:
      data:
        existingClaim: kanidm
        advancedMounts:
          kanidm:
            app:
              - path: /data
                subPath: data
      certs:
        type: secret
        name: idm-erwanleboucher-dev-tls
        defaultMode: 0400
        advancedMounts:
          kanidm:
            app:
              - path: /certs
      tmpfs:
        type: emptyDir
        advancedMounts:
          kanidm:
            app:
              - path: /var/run
      icon-cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          provision:
            app:
              - path: /data/icons
    route:
      app:
        hostnames:
          - idm.erwanleboucher.dev
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        controller: kanidm
        ports:
          http:
            port: 8443
          ldap:
            port: 3636
