---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kanidm
spec:
  chartRef:
    kind: OCIRepository
    name: kanidm
  interval: 30m
  values:
    controllers:
      kanidm:
        replicas: 1
        type: statefulset
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: docker.io/kanidm/server
              tag: 1.9.2
            env:
              KANIDM_ADMIN_BIND_PATH: /var/run/kanidmd.sock
              KANIDM_BINDADDRESS: "[::]:8443"
              KANIDM_DB_PATH: /data/kanidm.db
              KANIDM_DOMAIN: idm.erwanleboucher.dev
              KANIDM_LDAPBINDADDRESS: "[::]:3636"
              KANIDM_ORIGIN: https://idm.erwanleboucher.dev
              KANIDM_TLS_CHAIN: /certs/tls.crt
              KANIDM_TLS_KEY: /certs/tls.key
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      provision:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: ghcr.io/m00nwtchr/kanidm-provision
              tag: main@sha256:c94a5176f765d9bd0e094570022b9b64a6c683d5a847de8bd229c5f56eaf7c72
            env:
              KANIDM_INSTANCE: https://idm.erwanleboucher.dev
              KANIDM_NAMESPACE: security
              KANIDM_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: kanidm-provision-token
                    key: token
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 100Mi
            securityContext:
              capabilities:
                drop:
                  - ALL
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          kanidm:
            app:
              - path: /data
                subPath: data
      certs:
        type: secret
        name: idm-erwanleboucher-dev-tls
        defaultMode: 400
        advancedMounts:
          kanidm:
            app:
              - path: /certs
      empty:
        type: emptyDir
        globalMounts:
          - path: /var/run
      icon-cache:
        accessMode: ReadWriteOnce
        size: 1Gi
        suffix: icon-cache
        advancedMounts:
          provision:
            app:
              - path: /data/icons
    rbac:
      roles:
        kanidm-write-secret:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - "secrets"
              verbs:
                - "create"
                - "patch"
        kanidm-read-cm:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - "configmaps"
              verbs:
                - "get"
                - "list"
                - "watch"
      bindings:
        kanidm-write-secret:
          type: ClusterRoleBinding
          roleRef:
            identifier: kanidm-write-secret
          subjects:
            - identifier: kanidm
        kanidm-read-cm:
          type: ClusterRoleBinding
          roleRef:
            identifier: kanidm-read-cm
          subjects:
            - identifier: kanidm
    route:
      app:
        hostnames:
          - idm.erwanleboucher.dev
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        controller: kanidm
        ports:
          http:
            port: 8443
          ldap:
            port: 3636
    serviceAccount:
      kanidm: {}
