---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rathole
spec:
  interval: 1h
  path: ./kubernetes/apps/network/rathole/app
  postBuild:
    substitute:
      APP: rathole
      APP_NAMESPACE: network
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
