---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: vps-node-exporter
  namespace: observability
spec:
  staticConfigs:
    - targets:
        - newt-vps-node-exporter.network.svc.cluster.local:9100
  relabelings:
    - targetLabel: job
      replacement: node-exporter
    - targetLabel: instance
      replacement: pangolin-vps
    - targetLabel: nodename
      replacement: vps
