---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kubevirt.io/virtualmachine_v1.json
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: home-assistant
    spec:
      evictionStrategy: None
      nodeSelector:
        kubernetes.io/hostname: le-havre
      domain:
        cpu:
          cores: 2
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:
            - name: haos-disk
              disk:
                bus: virtio
          hostDevices:
            - deviceName: kubevirt.io/bluetooth
              name: bluetooth
          interfaces:
            - macAddress: "02:00:00:00:00:01"
              masquerade: {}
              name: default
              ports:
                - name: http
                  port: 8123
            - bridge: {}
              macAddress: "02:00:00:00:00:02"
              name: lan
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: home-assistant-lan
          name: lan
      volumes:
        - name: haos-disk
          dataVolume:
            name: haos-disk
  dataVolumeTemplates:
    - metadata:
        name: haos-disk
      spec:
        source:
          http:
            # renovate: datasource=github-releases depName=home-assistant/operating-system
            url: "https://github.com/home-assistant/operating-system/releases/download/17.1/haos_ova-17.1.qcow2.xz"
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 32Gi
          storageClassName: longhorn
