---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
spec:
  chartRef:
    kind: OCIRepository
    name: newt
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    controllers:
      newt:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          newt-sidecar:
            image:
              repository: ghcr.io/home-operations/newt-sidecar
              tag: 0.0.2
            args:
              - --gateway-name=kgateway-external
              - --site-id=buttery-deinagkistrodon
              - --target-hostname=kgateway-external.network.svc.cluster.local
              - --deny-countries=RU,CN,KP,IR,BY,IL
            restartPolicy: Always
            resources:
              limits:
                memory: 64Mi
        containers:
          app:
            image:
              repository: fosrl/newt
              tag: 1.10.2
            env:
              PANGOLIN_ENDPOINT:
                valueFrom:
                  secretKeyRef:
                    name: newt-secret
                    key: NEWT_SERVER_URL
              NEWT_ID:
                valueFrom:
                  secretKeyRef:
                    name: newt-secret
                    key: NEWT_ID
              NEWT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: newt-secret
                    key: NEWT_SECRET
              BLUEPRINT_FILE: /etc/newt/blueprint.yaml
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi

    rbac:
      roles:
        newt:
          type: ClusterRole
          rules:
            - apiGroups:
                - gateway.networking.k8s.io
              resources:
                - httproutes
              verbs:
                - get
                - watch
                - list
      bindings:
        newt:
          type: ClusterRoleBinding
          roleRef:
            identifier: newt
          subjects:
            - identifier: newt
    serviceAccount:
      newt: {}
    persistence:
      blueprint:
        type: emptyDir
        globalMounts:
          - path: /etc/newt
