---
apiVersion: v1
kind: Service
metadata:
  name: newt-vps-node-exporter
  namespace: network
spec:
  selector:
    app.kubernetes.io/instance: newt
    newt.instance: main-tunnel
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
