---
name: pangolin
reference: refs/heads/main
working_dir: vps
force_image_pull: true
external_secrets:
  OVH_APPLICATION_KEY: "op://kubernetes/ovh/OVH_APPLICATION_KEY"
  OVH_APPLICATION_SECRET: "op://kubernetes/ovh/OVH_APPLICATION_SECRET"
  OVH_CONSUMER_KEY: "op://kubernetes/ovh/OVH_CONSUMER_KEY"
  PANGOLIN_SECRET: "op://kubernetes/pangolin/server_secret"
  MAXMIND_ACCOUNT_ID: "op://kubernetes/pangolin/maxmind_account_id"
  MAXMIND_LICENSE_KEY: "op://kubernetes/pangolin/maxmind_key"
