---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: jellyseerr
  interval: 1h
  values:
    controllers:
      jellyseerr:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        type: deployment
        containers:
          app:
            image:
              repository: seerr/seerr
              tag: v3.2.0
            env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: LOG_LEVEL
                value: "debug"
              - name: TZ
                value: "Europe/Paris"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: 5055
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: jellyseerr
        ports:
          http:
            port: 5055
            protocol: TCP
    route:
      app:
        parentRefs:
          - name: envoy-external
            namespace: network
        hostnames:
          - request.erwanleboucher.dev
        rules:
          - backendRefs:
              - name: jellyseerr-anubis
                port: 8080

    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/config
