---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/rbac.authorization.k8s.io/rolebinding_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgejo-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forgejo-runner
subjects:
  - kind: ServiceAccount
    name: forgejo-runner
