---
name: Mirror to GitHub

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: https://data.forgejo.org/actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Mirror to GitHub
        env:
          GH_MIRROR_TOKEN: ${{ secrets.GH_MIRROR_TOKEN }}
        run: |-
          git push --prune "https://${GH_MIRROR_TOKEN}@github.com/eleboucher/homelab.git" \
            '+refs/remotes/origin/*:refs/heads/*' \
            'refs/tags/*:refs/tags/*'
