---
name: Mirror to GitHub

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: https://data.forgejo.org/actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Mirror to GitHub
        env:
          GH_MIRROR_TOKEN: ${{ secrets.GH_MIRROR_TOKEN }}
        run: |-
          git push "https://${GH_MIRROR_TOKEN}@github.com/eleboucher/homelab.git" \
            'HEAD:refs/heads/main'
