---
apiVersion: v1
kind: ConfigMap
metadata:
  name: janitorr-config
  namespace: media
data:
  application.yml: |-
    logging:
      level:
        com.github.schaka: INFO
      file:
        name: "/logs/janitorr.log"

    file-system:
      access: false

    application:
      dry-run: false
      run-once: false
      whole-tv-show: false
      whole-show-seeding-check: false
      leaving-soon: 14d
      leaving-soon-threshold-offset-percent: 5
      exclusion-tags:
        - "janitorr_keep"

      media-deletion:
        enabled: true
        movie-expiration:
          100: 180d
        season-expiration:
          100: 90d

      tag-based-deletion:
        enabled: false

      episode-deletion:
        enabled: true
        clean-older-seasons: false
        tag: janitorr_daily
        max-episodes: 10
        max-age: 30d

    clients:
      default:
        connect-timeout: 60s
        read-timeout: 60s
        level: NONE

      sonarr:
        enabled: true
        url: "http://sonarr:8989"
        delete-empty-shows: false
        determine-age-by: MOST_RECENT
        import-exclusions: false

      radarr:
        enabled: true
        url: "http://radarr:7878"
        only-delete-files: false
        determine-age-by: most_recent
        import-exclusions: false

      bazarr:
        enabled: true
        url: "http://bazarr:6767"

      jellyfin:
        enabled: true
        url: "http://jellyfin:8096"
        delete: true
        exclude-favorited: true
        leaving-soon-tv: "Shows (Leaving Soon)"
        leaving-soon-movies: "Movies (Leaving Soon)"
        leaving-soon-type: MOVIES_AND_TV

      jellyseerr:
        enabled: true
        url: "http://jellyseerr:5055"
        match-server: false

      streamystats:
        enabled: true
        whole-tv-show: false
        url: "http://streamystats-job-server:80"
