---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: janitorr-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: janitorr-secret
    template:
      data:
        CLIENTS_SONARR_API_KEY: "{{ .sonarr_api_key }}"
        CLIENTS_RADARR_API_KEY: "{{ .radarr_api_key }}"
        CLIENTS_BAZARR_API_KEY: "{{ .bazarr_api_key }}"
        CLIENTS_JELLYFIN_API_KEY: "{{ .jellyfin_api_key }}"
        CLIENTS_JELLYFIN_USERNAME: "{{ .jellyfin_username }}"
        CLIENTS_JELLYFIN_PASSWORD: "{{ .jellyfin_password }}"
        CLIENTS_JELLYSEERR_API_KEY: "{{ .jellyseerr_api_key }}"
        CLIENTS_STREAMYSTATS_API_KEY: "{{ .jellyfin_api_key }}"

  dataFrom:
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: bazarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "bazarr_$1"
    - extract:
        key: jellyfin
      rewrite:
        - regexp:
            source: "(.*)"
            target: "jellyfin_$1"
    - extract:
        key: jellyseerr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "jellyseerr_$1"
