---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: streamystats-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: streamystats-secret
    template:
      data:
        SESSION_SECRET: "{{ .session_secret }}"
  dataFrom:
    - extract:
        key: streamystats-secret
