---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wizarr
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: wizarr
  interval: 1h
  values:
    controllers:
      wizarr:
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/wizarrrr/wizarr
              tag: v2026.2.1
            env:
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: DISABLE_BUILTIN_AUTH
                value: "false"
              - name: TZ
                value: "Europe/Paris"
              - name: GUNICORN_WORKERS
                value: "1"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5690
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5690
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5690
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
            resources:
              requests:
                cpu: 15m
                memory: 200Mi
              limits:
                memory: 500Mi
    service:
      app:
        controller: wizarr
        ports:
          http:
            port: 5690
            protocol: TCP
    route:
      app:
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - wizarr.erwanleboucher.dev
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
