---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-factory
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/image-factory/app
  postBuild:
    substitute:
      APP: image-factory
      APP_NAMESPACE: automation
      SUBDOMAIN: factory
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: image-factory
      namespace: automation
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: automation
  timeout: 5m
