---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rathole-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rathole-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client.toml: |
          [client]
          remote_addr = "tunnel.erwanleboucher.dev:2333"

          [client.services.forgejo-ssh]
          token = "{{ .forgejo_ssh_token }}"
          local_addr = "envoy-external.network.svc.cluster.local:2222"
  data:
    - secretKey: forgejo_ssh_token
      remoteRef:
        key: rathole
        property: forgejo_ssh_token
