---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-drive-backup
  namespace: backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: google-drive-backup
    creationPolicy: Owner
  data:
    - secretKey: rclone.conf
      remoteRef:
        key: google-drive
        property: rclone_conf
