---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-s3
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flux-s3-secret
    template:
      data:
        accesskey: "{{ .accessKey }}"
        secretkey: "{{ .secretKey }}"
  dataFrom:
    - extract:
        key: ovh-k8s-schema-s3
