---
working_dir: ./docker/vps
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
force_recreate: false
external_secrets:
  OVH_APPLICATION_KEY: "op://kubernetes/ovh/OVH_APPLICATION_KEY"
  OVH_APPLICATION_SECRET: "op://kubernetes/ovh/OVH_APPLICATION_SECRET"
  OVH_CONSUMER_KEY: "op://kubernetes/ovh/OVH_CONSUMER_KEY"
  ANUBIS_ED25519_PRIVATE_KEY_HEX: "op://kubernetes/anubis/ED25519_PRIVATE_KEY_HEX"
  OVH_S3_ENDPOINT: "op://kubernetes/ovh-cnpg-backup/S3_ENDPOINT"
  OVH_S3_ACCESS_KEY_ID: "op://kubernetes/ovh-cnpg-backup/AWS_ACCESS_KEY_ID"
  OVH_S3_SECRET_ACCESS_KEY: "op://kubernetes/ovh-cnpg-backup/AWS_SECRET_ACCESS_KEY"
  VPS_IP: "op://kubernetes/towonel-tunnel/ip"
  VPS_ADD_IP: "op://kubernetes/towonel-tunnel/add_ip"
  TOWONEL_ACME_EMAIL: "op://kubernetes/towonel-hub/acme_email"
  TOWONEL_INVITE_HASH_KEY: "op://kubernetes/towonel-hub/invite_hash"
  TOWONEL_EDGE_INVITE_TOKEN: "op://kubernetes/towonel-hub/edge_invite_token"
  FORGEJO_RUNNER_UUID: "op://kubernetes/forgejo-runner-vps/uuid"
  FORGEJO_RUNNER_TOKEN: "op://kubernetes/forgejo-runner-vps/token"
  FORGEJO_RUNNER_FREEK_TOKEN: "op://kubernetes/forgejo-runner-freek/token"
  RATHOLE_FORGEJO_SSH_TOKEN: "op://kubernetes/rathole/forgejo_ssh_token"
