---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie
spec:
  components:
    - ../../../../components/oidc
    - ../../../../components/postgres/cert
    - ../../../../components/volsync
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/apps/selfhosted/mealie/app
  postBuild:
    substitute:
      APP: *app
      APP_NAMESPACE: selfhosted
      OIDC_CALLBACK: /login
      OIDC_DISPLAY_NAME: Mealie
      OIDC_LEGACY_CRYPTO: "true"
      OIDC_SHORT_USERNAME: "true"
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
