---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  components:
    - ../../../../components/volsync
    - ../../../../components/oidc
    - ../../../../components/postgres/cert
  dependsOn:
    - name: cnpg-cluster
      namespace: database
    - name: dragonfly
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./kubernetes/apps/selfhosted/paperless/app"
  postBuild:
    substitute:
      APP: paperless
      APP_NAMESPACE: selfhosted
      APP_UID: "1000"
      APP_GID: "65542"
      VOLSYNC_CAPACITY: 15Gi
      OIDC_DISPLAY_NAME: "Paperless"
      OIDC_CALLBACK: /accounts/oidc/kanidm/login/callback/
      OIDC_DISABLE_PKCE: "true"
      OIDC_IMAGE_NAME: paperless-ngx
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
