---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: vps-node-exporter
  namespace: observability
spec:
  staticConfigs:
    - targets:
        - newt.network.svc.cluster.local:9100
  relabelings:
    - action: replace
      replacement: node-exporter
      targetLabel: job
    - action: replace
      replacement: vps.internal:9100
      targetLabel: instance
    - action: replace
      replacement: vps
      targetLabel: nodename
