---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/toolhive.stacklok.dev/virtualmcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway
spec:
  authServerConfig:
    issuer: https://mcp.erwanleboucher.dev
    signingKeySecretRefs:
      - name: vmcp-auth-server-secret
        key: signing-key
    hmacSecretRefs:
      - name: vmcp-auth-server-secret
        key: hmac-key
    tokenLifespans:
      accessTokenLifespan: 1h
      refreshTokenLifespan: 168h
      authCodeLifespan: 10m
    upstreamProviders:
      - name: kanidm
        type: oidc
        oidcConfig:
          issuerUrl: https://idm.erwanleboucher.dev/oauth2/openid/toolhive
          clientId: toolhive
          clientSecretRef:
            name: kanidm-toolhive-oidc
            key: client-secret
          redirectUri: https://mcp.erwanleboucher.dev/oauth/callback
          scopes:
            - openid
            - profile
            - email
  groupRef:
    name: mcp-tools
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
  embeddingServerRef:
    name: mcp-tools-embedding
  incomingAuth:
    type: oidc
    oidcConfigRef:
      name: external-oidc
      audience: https://mcp.erwanleboucher.dev/mcp
      resourceUrl: https://mcp.erwanleboucher.dev/mcp
  outgoingAuth:
    source: discovered
  sessionStorage:
    provider: redis
    address: dragonfly.database:6379
  podTemplateSpec:
    spec:
      containers:
        - name: vmcp
          env:
            - name: INSECURE_DISABLE_URL_VALIDATION
              value: "true"
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/toolhive.stacklok.dev/virtualmcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-internal
spec:
  groupRef:
    name: mcp-tools
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}_"
  embeddingServerRef:
    name: mcp-tools-embedding
  incomingAuth:
    type: anonymous
  outgoingAuth:
    source: discovered
