---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: image-factory
spec:
  chartRef:
    kind: OCIRepository
    name: image-factory
  interval: 1h
  values:
    fullnameOverride: image-factory

    cacheSigningKey:
      existingSecret: image-factory-cache-signing-key

    extraVolumes:
      - name: registry-auth
        secret:
          secretName: image-factory-registry-auth
          items:
            - key: .dockerconfigjson
              path: config.json
    extraVolumeMounts:
      - name: registry-auth
        mountPath: /home/nonroot/.docker/config.json
        subPath: config.json
        readOnly: true
    env:
      - name: DOCKER_CONFIG
        value: /home/nonroot/.docker

    config:
      artifacts:
        core:
          registry: ghcr.io
          components:
            installer: eleboucher/installer
            installerBase: eleboucher/installer-base
            imager: eleboucher/imager
            extensionManifest: siderolabs/extensions
            overlayManifest: siderolabs/overlays
            talosctl: siderolabs/talosctl-all

        installer:
          internal:
            registry: ghcr.io
            namespace: eleboucher
            repository: installer

        schematic:
          registry: ghcr.io
          namespace: eleboucher
          repository: schematics

      containerSignature:
        disabled: true

      build:
        minTalosVersion: "1.13.0"

      http:
        externalURL: https://factory.erwanleboucher.dev/
        externalPXEURL: https://pxe-factory.erwanleboucher.dev/

    gatewayApi:
      ui:
        enabled: true
        hostnames:
          - factory.erwanleboucher.dev
        parentRefs:
          - name: envoy-external
            namespace: network
      pxe:
        enabled: true
        hostnames:
          - pxe-factory.erwanleboucher.dev
        parentRefs:
          - name: envoy-external
            namespace: network

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
