---
endpoint: "https://registry.erwanleboucher.dev"
accountDomain: "erwanleboucher.dev"
listen: ":5000"
dataDir: "/apoci/storage"
logFormat: json

database:
  driver: postgres
  dsn: "postgres://apoci:apoci@apoci-postgres:5432/apoci?sslmode=disable"

peering:
  healthCheckInterval: 30s
  fetchTimeout: 60s

metrics:
  enabled: true
  listen: ":9090"

federation:
  autoAccept: mutual

upstreams:
  enabled: true
  registries:
    - name: docker.io
      endpoint: "https://registry-1.docker.io"
    - name: ghcr.io
      endpoint: "https://ghcr.io"

ui:
  enabled: true
