---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

resources:
  - namespace.yaml
  - context7-mcp/ks.yaml
  - grafana-mcp/ks.yaml
  - memory-mcp/ks.yaml
  - ollama/ks.yaml
  - toolhive/ks.yaml
  - victoria-logs-mcp/ks.yaml
