# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qui
  namespace: flux-system
spec:
  components:
    - ../../../../components/oidc
    - ../../../../components/volsync
    - ../../../../components/nfs-scaler
  interval: 1h
  path: ./kubernetes/apps/downloads/qui/app
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: longhorn
      namespace: longhorn-system
  postBuild:
    substitute:
      APP: qui
      APP_NAMESPACE: downloads
      OIDC_CALLBACK: /api/auth/oidc/callback
      OIDC_GROUP: admins
      OIDC_LEGACY_CRYPTO: "true"
      OIDC_SHORT_USERNAME: "true"
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_SCHEDULE: "20 1-23/2 * * *"
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
