---
name: rathole
services:
  rathole-init:
    image: docker.io/library/alpine:3.23
    container_name: rathole-init
    restart: "no"
    command:
      - /bin/sh
      - -c
      - apk add --no-cache gettext && envsubst < /tmpl/server.toml.tmpl > /config/server.toml.tmp && mv /config/server.toml.tmp /config/server.toml
    environment:
      - RATHOLE_FORGEJO_SSH_TOKEN
    volumes:
      - ./server.toml.tmpl:/tmpl/server.toml.tmpl:ro
      - rathole-config:/config

  rathole:
    networks:
      default:
        ipv4_address: 172.21.0.2
    # renovate: datasource=docker depName=rapiz1/rathole
    image: docker.io/rapiz1/rathole:v0.5.0
    container_name: rathole
    restart: unless-stopped
    command:
      - --server
      - /etc/rathole/server.toml
    depends_on:
      rathole-init:
        condition: service_completed_successfully
    ports:
      - "${VPS_IP}:2222:2222"
      - "${VPS_IP}:2333:2333"
    volumes:
      - rathole-config:/etc/rathole:ro
    labels:
      - prometheus.scrape=false

volumes:
  rathole-config:

networks:
  default:
    name: edge
    external: true
