---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-issuer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ovh-issuer-secret
  data:
    - secretKey: applicationKey
      remoteRef:
        key: ovh-certmanager
        property: OVH_APPLICATION_KEY
    - secretKey: applicationSecret
      remoteRef:
        key: ovh-certmanager
        property: OVH_APPLICATION_SECRET
    - secretKey: consumerKey
      remoteRef:
        key: ovh-certmanager
        property: OVH_CONSUMER_KEY
