---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wg-portal-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wg-portal-secret
    creationPolicy: Owner
  data:
    - secretKey: MIKROTIK_USER
      remoteRef:
        key: wg-portal
        property: mikrotik_user
    - secretKey: MIKROTIK_PASSWORD
      remoteRef:
        key: wg-portal
        property: mikrotik_password
    - secretKey: MIKROTIK_SERVER_PUBKEY
      remoteRef:
        key: wg-portal
        property: mikrotik_server_pubkey
