---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: obsidian-livesync
spec:
  chartRef:
    kind: OCIRepository
    name: obsidian-livesync
  interval: 30m
  values:
    controllers:
      obsidian-livesync:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: couchdb
              tag: 3.5.1
            env:
              TZ: "Europe/Paris"
            envFrom:
              - secretRef:
                  name: obsidian-livesync
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /_up
                    port: &port 5984
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  httpGet:
                    path: /_up
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 5984
            runAsGroup: 5984
            fsGroup: 5984
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault

    service:
      app:
        controller: obsidian-livesync
        ports:
          http:
            port: *port

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /opt/couchdb/data
      local-config:
        type: configMap
        name: obsidian-livesync
        globalMounts:
          - path: /opt/couchdb/etc/local.ini
            subPath: local.ini
            readOnly: true

    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 401"]
        hostnames:
          - obsidian-livesync.erwanleboucher.dev
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    configMaps:
      config:
        data:
          local.ini: |-
            [couchdb]
            single_node=true
            max_document_size = 50000000

            [chttpd]
            require_valid_user_except_for_up = true
            max_http_request_size = 4294967296
            enable_cors = true

            [chttpd_auth]
            require_valid_user = true

            [httpd]
            WWW-Authenticate = Basic realm="couchdb"
            bind_address = 0.0.0.0

            [cors]
            credentials = true
            headers = accept, authorization, content-type, origin, referer
            methods = GET, PUT, POST, HEAD, DELETE
            origins = app://obsidian.md, capacitor://localhost, http://localhost
