---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bluesky
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: bluesky
  components:
    - ../../../../components/postgres/cert
    - ../../../../components/volsync
  dependsOn:
    - name: garage
      namespace: garage-system
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: "./kubernetes/apps/selfhosted/bluesky/app"
  postBuild:
    substitute:
      APP: bluesky
      APP_NAMESPACE: selfhosted
      VOLSYNC_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
