---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/pangolin.home-operations.com/privateresource_v1alpha1.json
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PrivateResource
metadata:
  name: cluster-pods
  namespace: network
spec:
  name: Cluster Pod Network
  siteRef: homelab
  mode: cidr
  destination: 10.42.0.0/16
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/pangolin.home-operations.com/privateresource_v1alpha1.json
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PrivateResource
metadata:
  name: cluster-services
  namespace: network
spec:
  name: Cluster Service Network
  siteRef: homelab
  mode: cidr
  destination: 10.43.0.0/16
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/pangolin.home-operations.com/privateresource_v1alpha1.json
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PrivateResource
metadata:
  name: cluster-nodes
  namespace: network
spec:
  name: Cluster Node Network
  siteRef: homelab
  mode: cidr
  destination: 192.168.1.0/24
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/pangolin.home-operations.com/privateresource_v1alpha1.json
apiVersion: pangolin.home-operations.com/v1alpha1
kind: PrivateResource
metadata:
  name: cluster-bgp
  namespace: network
spec:
  name: Cluster BGP Network
  siteRef: homelab
  mode: cidr
  destination: 192.168.69.0/24
