---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app continuwuity
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: continuwuity
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      continuwuity:
        containers:
          app:
            image:
              repository: forgejo.ellis.link/continuwuation/continuwuity
              tag: v0.5.6-maxperf
            env:
              TZ: "Europe/Paris"
              CONDUWUIT_SERVER_NAME: erwanleboucher.dev
              CONDUWUIT_ADDRESS: "::"
              CONDUWUIT_PORT: &port 8080
              CONDUWUIT_DATABASE_PATH: /data
              CONDUWUIT_NEW_USER_DISPLAYNAME_SUFFIX: ""
              CONDUWUIT_WELL_KNOWN__CLIENT: "https://matrix.erwanleboucher.dev"
              CONDUWUIT_WELL_KNOWN__SERVER: "matrix.erwanleboucher.dev:443"
              CONDUWUIT_ALLOW_ENCRYPTION: true
              CONDUWUIT_ALLOW_FEDERATION: true
              CONDUWUIT_ALLOW_REGISTRATION: true
              CONDUWUIT_SUSPEND_ON_REGISTER: true
              CONDUWUIT_FORGET_FORCED_UPON_LEAVE: true
              CONDUWUIT_REQUIRE_AUTH_FOR_PROFILE_REQUESTS: true
              CONDUWUIT_ALLOW_PUBLIC_ROOM_DIRECTORY_WITHOUT_AUTH: false
              CONDUWUIT_ALLOW_PUBLIC_ROOM_DIRECTORY_OVER_FEDERATION: false
              CONDUWUIT_LOCKDOWN_PUBLIC_ROOM_DIRECTORY: true
              CONDUWUIT_ALLOW_LEGACY_MEDIA: false
              CONDUWUIT_QUERY_OVER_TCP_ONLY: true
              CONDUWUIT_IP_LOOKUP_STRATEGY: "1"
            envFrom:
              - secretRef:
                  name: continuwuity-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi

    service:
      app:
        controller: continuwuity
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "matrix.erwanleboucher.dev"
        parentRefs:
          - name: kgateway-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
