---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: barman-r2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        R2_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        R2_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
  dataFrom:
    - extract:
        key: cloudflare-r2
