---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kguardian
spec:
  chartRef:
    kind: OCIRepository
    name: kguardian
  interval: 30m
  values:
    broker:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/broker
        tag: v1.9.0@sha256:7b44d7b6a69b28d98dd1910ba29f6630357ca56e54a742d6c021cede765374d7
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
    controller:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/controller
        tag: v1.8.1@sha256:c122ee55e35cbc6df9e507d691641f5968b13cd07bec94ba87283ea431d8e358
      excludedNamespaces:
        - kguardian
    database:
      resources:
        limits:
          cpu: 6
    frontend:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/frontend
        tag: v1.9.0@sha256:32bb6300f51f0bdc3040d6bfa524c8ad56ecd27feb76fb28f9e46dcda7eede83
