---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kguardian
spec:
  chartRef:
    kind: OCIRepository
    name: kguardian
  interval: 30m
  values:
    broker:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/broker
        tag: v1.7.1@sha256:127de1eef64fe6de7d58d9c79a517097939b9c948c1f2bb74703008acbb080a9
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
    controller:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/controller
        tag: v1.8.1@sha256:c122ee55e35cbc6df9e507d691641f5968b13cd07bec94ba87283ea431d8e358
      excludedNamespaces:
        - kguardian
    database:
      resources:
        limits:
          cpu: 6
    frontend:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/frontend
        tag: v1.8.1@sha256:907633539cf641cd44eb19b47a6e5cd7688a7cf4685bc44e0d1b2c2b716ff608
