---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt-wg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: newt-wg-secret
    template:
      data:
        NEWT_ID: "{{ .newt_id }}"
        NEWTSC_SITE_ID: "{{ .newt_site_id }}"
        NEWT_SECRET: "{{ .newt_secret }}"
        PANGOLIN_ENDPOINT: "{{ .server_url }}"
  dataFrom:
    - extract:
        key: pangolin-wg
