---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt-wg
spec:
  chartRef:
    kind: OCIRepository
    name: newt-wg
  interval: 1h
  values:
    global:
      deploymentAnnotations:
        reloader.stakater.com/auto: "true"
      image:
        # renovate: datasource=github-releases depName=fosrl/newt
        tag: "1.10.3"
      nativeMode:
        enabled: true
      networkPolicy:
        enabled: false
      prometheusRule:
        enabled: true

    rbac:
      clusterRole: true

    serviceAccount:
      automountServiceAccountToken: true
      name: newt-wg

    newtInstances:
      - name: main-tunnel
        enabled: true
        replicas: 1
        pingInterval: 60s
        interface: "newt-wg"
        useNativeInterface: true
        acceptClients: true
        mtu: 1380
        auth:
          existingSecretName: newt-wg-secret
        extraEnv:
          NEWT_ADMIN_ADDR: "0.0.0.0:2112"
          NEWT_METRICS_PROMETHEUS_ENABLED: "true"
        metrics:
          port: 2112
          service:
            enabled: true
            port: 2112
          serviceMonitor:
            enabled: true
        service:
          enabled: true
