---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kromgo
spec:
  chartRef:
    kind: OCIRepository
    name: kromgo
  interval: 30m
  values:
    controllers:
      kromgo:
        pod:
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        strategy: RollingUpdate

        containers:
          kromgo:
            image:
              repository: ghcr.io/eleboucher/kromgo
              tag: main@sha256:fa81ca0d48c51831a7d34b7ce21a7b5db6259e1344ce9fb78bfb4ea05422fc0b
            env:
              PROMETHEUS_URL: http://vmsingle-victoria-metrics-cluster.observability.svc.cluster.local:8428
              SERVER_HOST: 0.0.0.0
              SERVER_PORT: &port 8080
              HEALTH_HOST: 0.0.0.0
              HEALTH_PORT: &hport 8888
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *hport
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources:
              requests:
                memory: 10M
              limits:
                memory: 64M
    persistence:
      config-file:
        type: configMap
        name: kromgo-configmap
        globalMounts:
          - path: /kromgo/config.yaml
            subPath: config.yaml
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames:
          - kromgo.erwanleboucher.dev
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - filters:
              - type: CORS
                cors:
                  allowOrigins:
                    - "*"
                  allowMethods:
                    - GET
                    - OPTIONS
                  allowHeaders:
                    - "*"
                  maxAge: 86400
            backendRefs:
              - name: kromgo
                port: *port

    service:
      app:
        ports:
          http:
            port: *port
            primary: true
          health:
            port: *hport
