---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: phanpy
spec:
  chartRef:
    kind: OCIRepository
    name: phanpy
  interval: 30m
  values:
    controllers:
      phanpy:
        containers:
          main:
            image:
              repository: "ghcr.io/jjgadgets/phanpy"
              tag: 2025.01.26.24f03f5
            env:
              PHANPY_WEBSITE: "phanpy.erwanleboucher.dev"
              PHANPY_DEFAULT_INSTANCE: "gts.erwanleboucher.dev"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    service:
      main:
        controller: phanpy
        ports:
          http:
            port: 8080
    route:
      app:
        parentRefs:
          - name: envoy-external
            namespace: network
        hostnames:
          - phanpy.erwanleboucher.dev
