---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bluesky-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bluesky-secret
    creationPolicy: Owner
    template:
      data:
        COCOON_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        COCOON_SESSION_SECRET: "{{ .SESSION_SECRET }}"
        COCOON_S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        COCOON_S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: bluesky
