---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bluesky
spec:
  chartRef:
    kind: OCIRepository
    name: bluesky
  interval: 1h
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

    controllers:
      bluesky:
        initContainers:
          init-keys:
            image:
              repository: ghcr.io/haileyok/cocoon
              tag: latest
            command:
              - /bin/sh
              - -c
              - |
                [ -f /keys/rotation.key ] || /cocoon create-rotation-key --out /keys/rotation.key
                [ -f /keys/jwk.key ] || /cocoon create-private-jwk --out /keys/jwk.key
            env: &env
              COCOON_CONTACT_EMAIL: "erwan@erwanleboucher.dev"
              COCOON_DID: "did:web:bluesky.erwanleboucher.dev"
              COCOON_HOSTNAME: "bluesky.erwanleboucher.dev"
              COCOON_JWK_PATH: /keys/jwk.key
              COCOON_RELAYS: "https://bsky.network"
              COCOON_ROTATION_KEY_PATH: /keys/rotation.key
            envFrom: &envFrom
              - secretRef:
                  name: bluesky-secret
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
        containers:
          app:
            image:
              repository: ghcr.io/haileyok/cocoon
              tag: latest
            workingDir: /data/cocoon
            env:
              !!merge <<: *env
              TZ: "Europe/Paris"
              COCOON_DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: bluesky-postgres
                    key: url
              COCOON_DB_TYPE: postgres
              COCOON_S3_BLOBSTORE_ENABLED: "true"
              COCOON_S3_BUCKET: bluesky
              COCOON_S3_ENDPOINT: "http://garage.garage-system.svc.cluster.local:3900"
              COCOON_S3_REGION: us-east-1
              COCOON_SMTP_EMAIL: "bluesky@erwanleboucher.dev"
              COCOON_SMTP_PORT: "587"
              COCOON_SMTP_NAME: "Bluesky"
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /xrpc/_health
                    port: 8080
                  failureThreshold: 3
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext: *securityContext

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          bluesky:
            app:
              - path: /data/cocoon
                subPath: data
              - path: /keys
                subPath: keys
            init-keys:
              - path: /keys
                subPath: keys
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

    route:
      app:
        hostnames:
          - "bluesky.erwanleboucher.dev"
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - name: bluesky
                port: 8080
            filters:
              - cors:
                  allowHeaders:
                    - "*"
                  allowMethods:
                    - "*"
                  allowOrigins:
                    - "*"
                  maxAge: 86400
                type: CORS

    service:
      app:
        controller: bluesky
        ports:
          http:
            port: 8080
