---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: trek-secret
    template:
      data:
        ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: trek
