---
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip-verify: true
      depth: 0

when:
  - branch: main
    event: push

steps:
  - name: Mirror to GitHub
    image: alpine/git:latest
    environment:
      MIRROR_TOKEN:
        from_secret: GH_MIRROR_TOKEN
    commands:
      - git remote add github "https://$${MIRROR_TOKEN}@github.com/eleboucher/homelab.git"
      - git push --force github main
