---
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip-verify: true
      depth: 0

when:
  - branch: main
    event: push

steps:
  - name: Mirror to GitHub
    image: alpine/git:latest
    environment:
      MIRROR_TOKEN:
        from_secret: GH_MIRROR_TOKEN
    commands:
      - git push --force-with-lease --force-if-includes "https://$${MIRROR_TOKEN}@github.com/eleboucher/homelab.git" HEAD:refs/heads/main
