---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: continuwuity-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: continuwuity-secret
    creationPolicy: Owner
    template:
      data:
        CONDUWUIT_REGISTRATION_TOKEN: "{{ .registration_token }}"
        CONDUWUIT_EMERGENCY_PASSWORD: "{{ .emergency_password }}"
        CONDUWUIT_TURN_SECRET: "{{ .turn_secret }}"
  dataFrom:
    - extract:
        key: continuwuity
