---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-secrets
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: discord-webhook-secrets
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: discord
        property: webhook_url
