---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-schemas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: k8s-schemas-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .accessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretKey }}"
  dataFrom:
    - extract:
        key: ovh-k8s-schema-s3
