---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: publish-k8s-schemas-secrets
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: publish-k8s-schemas-secret
    creationPolicy: Owner
    template:
      data:
        CLOUDFLARE_ACCOUNT_ID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
