---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-secret
    creationPolicy: Owner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        ssh_host_ed25519_key: "{{ .ssh_host_ed25519_key }}"
        smtp_relay_server: "{{ .smtp_relay_server }}"
        smtp_relay_username: "{{ .smtp_relay_username }}"
        smtp_relay_password: "{{ .smtp_relay_password }}"
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: smtp-relay-secret
