---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./ocirepository.yaml
  - ./pubresource.yaml
configMapGenerator:
  - name: forgejo-themes
    files:
      - themes/theme-anthracite.css
      - themes/theme-anthracite-dark.css
      - themes/theme-anthracite-light.css
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
