---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secrets
    creationPolicy: Owner
    template:
      data:
        HOMEPAGE_VAR_JELLYFIN_KEY: "{{ .jellyfin_key }}"
        HOMEPAGE_VAR_JELLYSEERR_KEY: "{{ .jellyseerr_key }}"
        HOMEPAGE_VAR_HASS_KEY: "{{ .hass_key }}"
        HOMEPAGE_VAR_SONARR_KEY: "{{ .sonarr_key }}"
        HOMEPAGE_VAR_RADARR_KEY: "{{ .radarr_key }}"
        HOMEPAGE_VAR_BAZARR_KEY: "{{ .bazarr_key }}"
        HOMEPAGE_VAR_PROWLARR_KEY: "{{ .prowlarr_key }}"
        HOMEPAGE_VAR_SABNZBD_KEY: "{{ .sabnzbd_key }}"
        HOMEPAGE_VAR_QBIT_USER: "{{ .qbit_user }}"
        HOMEPAGE_VAR_QBIT_PASS: "{{ .qbit_password }}"
        HOMEPAGE_VAR_MIKROTIK_USER: "{{ .mikrotik_user }}"
        HOMEPAGE_VAR_MIKROTIK_PASS: "{{ .mikrotik_pass }}"
        HOMEPAGE_VAR_AUTOBRR_KEY: "{{ .autobrr_key }}"
        HOMEPAGE_VAR_CF_ACCOUNT_ID: "{{ .account_id }}"
        HOMEPAGE_VAR_CF_TUNNEL_ID: "{{ .tunnel_id }}"
        HOMEPAGE_VAR_CF_API_KEY: "{{ .CLOUDFLARE_API_TOKEN }}"
        HOMEPAGE_VAR_GRAFANA_USER: "{{ .grafana_user }}"
        HOMEPAGE_VAR_GRAFANA_PASS: "{{ .grafana_password }}"
  dataFrom:
    - extract:
        key: homepage-secrets
    - extract:
        key: cloudflare
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: "(.*)"
            target: "grafana_$1"
    - extract:
        key: qbit
      rewrite:
        - regexp:
            source: "(.*)"
            target: "qbit_$1"
