---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pangolin-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pangolin-operator-secret
    template:
      data:
        PANGOLIN_API_URL: "{{ .api_url }}"
        PANGOLIN_ENDPOINT: "{{ .server_url }}"
        PANGOLIN_API_KEY: "{{ .api_key }}"
        PANGOLIN_ORG_ID: "{{ .org_id }}"
  dataFrom:
    - extract:
        key: pangolin-operator
