---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pangolin-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.0
    digest: sha256:c54254c4f6d9de3e369579b31c153f8ea856b7e3ae1e235c245ae4f7accf94b4
  url: oci://ghcr.io/eleboucher/charts/pangolin-operator
