---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

resources:
  # - cloudflared/ks.yaml
  - echo/ks.yaml
  - external-dns/ks.yaml
  - kgateway/ks.yaml
  - namespace.yaml
  - newt-wg/ks.yaml
  - newt/ks.yaml
